"""empty message

Revision ID: c5b2eccfb412
Revises: e88bc41bcc07
Create Date: 2024-02-01 11:36:02.122981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b2eccfb412'
down_revision = 'e88bc41bcc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.drop_index('ix_weight_yard')
        batch_op.drop_column('typ')
        batch_op.drop_column('rbook')
        batch_op.drop_column('yard')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yard', sa.VARCHAR(length=8), nullable=True))
        batch_op.add_column(sa.Column('rbook', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('typ', sa.VARCHAR(length=1), nullable=True))
        batch_op.create_index('ix_weight_yard', ['yard'], unique=False)

    # ### end Alembic commands ###
